# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/circadian',
                'doc_host': 'https://khannay.github.io',
                'git_url': 'https://github.com/khannay/circadian',
                'lib_path': 'circadian'},
  'syms': {'circadian.core': {'circadian.core.foo': ('core.html#foo', 'circadian/core.py')}}}
