project:
  type: website

format:
  html:
    theme: pulse
    css: styles.css
    toc: true

website:
  twitter-card: true
  open-graph: true
  repo-actions: [issue]
  navbar:
    background: primary
    search: true
    right:
      - icon: github
        href: https://github.com/Arcascope/circadian
      - icon: twitter
        href: https://twitter.com/arcascope
  sidebar:
    style: floating
  favicon: favicon.png
  
metadata-files: [nbdev.yml, sidebar.yml]